### ISSUE TITLE
crash upon loading .so lib with gdb

### ISSUE THREAD

**Issue by fipso** [elysian6969/elysium#13]
hi,
i was trying to build the project using `cargo build -r`, but upon loading the lib with gdb:
```bash
sudo gdb \
    -ex "set auto-load safe-path /usr/lib/" \
    -ex "attach $csgo_pid" \
    -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
    -ex "call \$dlopen(\"/usr/lib/$libname\", 1)"
```
the game just crashes.
I assume i am building for the wrong target, because on win you build csgo .dlls as 32bit ?
build with `--target=i586-unknown-linux-gnu` results in akward rust macro erros.

can you share your cargo build command and way of injection please ?
thanks in advance

EDIT:
i am totally wrong. building with cargo build -r is totally fine injecting with gdb also works, but still the game crashed upon injecting. i will try to debug with gdb to find out what is causing the crash and will update this issue accordingly.

**Comment by elysian6969** [comment]
crash is from dumb changes i made

```rust
let address = self.vtable.frame_stage_notify as *const ();

&address as *const *const () as *const u8
```

which isnt an address to fsn lol. just fixed that with an update and used ptr::addr_of instead, which can't be fucked up as easily kek

```rust
ptr::addr_of!(self.vtable.frame_stage_notify).cast()
```

**Comment by elysian6969** [comment]
oh also yeah this is only for csgo_linux64, so `--target=x86_64-unknown-linux-gnu`
