### ISSUE TITLE
iced ui not rendering correctly

### ISSUE THREAD

**Issue by fipso** [elysian6969/elysium#14]
![image](https://user-images.githubusercontent.com/8930842/184538718-10ee2ba8-b8c8-4b59-816d-3476ea16460d.png)

iced ui only shows 3 white lines.
archlinux, tryed with release/debug build

ty

EDIT:
i should see an empty iced container am i right ?

**Comment by elysian6969** [comment]
yeah, iced updated again, i was lazy to get things working again so i deleted it, temporarily

well anyways, added it all again, and now it's actually functional, rofl, before it was nothing more than a demo of it working

cheers for motivating me into working on this again

**Comment by fipso** [comment]
seems like you broke build somehow

![image](https://user-images.githubusercontent.com/8930842/184630916-947b203d-e591-4452-a384-c01c22da9787.png)

**Comment by elysian6969** [comment]
LOL i forgot Cargo.toml
