### ISSUE TITLE
how to show cursor

### ISSUE THREAD

**Issue by elysian6969** [elysian6969/elysium#15]
currently, the only way im aware of achieving this is via `drawgui 0` and opening the console

**Comment by elysian6969** [comment]
local testing has revealed that `InputSystem.reset_cursor_visible()` will hide the cursor, even if shown while the console is open :raised_eyebrow:

**Comment by elysian6969** [comment]
`cl_mouseenable 1`/`0` seems like it does nothing, after panorama came into existence

**Comment by codecheck01** [comment]
lock_cursor hook probably.

**Comment by elysian6969** [comment]
hmmm, osiris hooks it for win only

https://github.com/danielkrupinski/Osiris/blob/master/Source/Hooks.cpp#L639-L644

**Comment by elysian6969** [comment]
https://github.com/danielkrupinski/Osiris/pull/3365 :raised_eyebrow:

**Comment by elysian6969** [comment]
`Surface.unlock_cursor()` doesn't do much on linux it seems (used within lock_cursor hooks)
