### ISSUE TITLE
Any ideas for a better alternative?

### ISSUE THREAD

**Issue by codecheck01** [elysian6969/elysium#16]
I have something similar and I don't know if there is something cleaner than this 🤔

https://github.com/elysian6969/elysium/blob/master/src/lib.rs#L121-L124

**Comment by elysian6969** [comment]
most likely a builder,
```rust
let mut hooks = Hooks::builder(); // HooksBuilder

hooks.create_move(blah):
hooks.build(); // Hooks
```
it's just somewhat of a pita to write lol

**Comment by codecheck01** [comment]
@elysian6969 Thank you so much for the last commit, you are obviously better than me with Rust, and you help me at understanding some things with you base.

**Comment by elysian6969** [comment]
haha surely not, this project isnt exactly new, just been going through trial and error
