### ISSUE TITLE
fsn can be called before hooks is fully initialized, thus unwrap() fails

### ISSUE THREAD

**Issue by elysian6969** [elysian6969/elysium#17]

**Comment by codecheck01** [comment]
Yep randomly crashing, fix priority.

**Comment by codecheck01** [comment]
https://github.com/elysian6969/elysium/blob/7f19ce915027fe53a1a955bc7e74dcdce49e4c5d/src/lib.rs#L122-L124

I can't find the reason why I am crashing 1 time on 20 - 30 tries, there is an UB that I don't understand.
