### ISSUE TITLE
add teamid to networkable

### ISSUE THREAD

**Issue by fipso** [elysian6969/elysium#18]
teamid is part of baseentity struct, but its not accessible using networkable.
tryed implementing it myself, but am segfaulting

**Comment by elysian6969** [comment]
yeah for some reason some fuckery seems to happen with renderable and networkable, things work as expected with a println! rofl. might do some changes to entitylist to provide access via some `EntityRef<'a>` type

**Comment by elysian6969** [comment]
wait are you looking for `m_iTeamNum`?

**Comment by elysian6969** [comment]
because theres also `Entity::team` which returns `Team`?

https://github.com/elysian6969/elysium/blob/master/src/entity.rs#L183
https://github.com/elysian6969/elysium/blob/master/crates/sdk/src/entity.rs#L51

**Comment by fipso** [comment]
hi, yeah i was looking for m_iTeamNum to build team based chams etc, but now u already did that thanks :smile:
